### ISSUE TITLE
Recirculating a packet to multiple pipeline

### ISSUE THREAD

**Issue by drobinkent** [barefootnetworks/Open-Tofino#23]
Assume a tofino switch with n pieplines. If we recirculate a packet from a pipeline is it possible to send that recirculated packet to every pipeline?

**Comment by vgurevich** [comment]
@drobinkent -- recirculation in TNA is the same as sending a packet to a port that is in the loopback. 

If you want to recirculate a packet so that the recirculated copy goes to each and every pipeline (i.e. you want to produce `n` copies of the packet) you can easily do that by sending a packet to a multicast group instead of a single unicast port.

Please, direct your further questions to the appropriate Intel support forums:
* Intel Premier Support (for commercial customer)
* ICRP Forum (for the Academic customers)
