### ISSUE TITLE
P4 Tofino Example Programs?

### ISSUE THREAD

**Issue by fruffy** [barefootnetworks/Open-Tofino#24]
This repository contained quite a few Tofino 1 (or 2) example programs, but they seem to have been removed. Is there a reason for this?

**Comment by vgurevich** [comment]
@fruffy -- yes, there is a specific reason why the examples were removed.

As mentioned in the README.md, the files in this repo are licensed under Creative Commons Attribution-NoDerivs (CC BY-ND 4.0) license (https://creativecommons.org/licenses/by-nd/4.0/legalcode). 

This license is quite appropriate for publishing the interfaces (they are open, but at the same time we do not allow them to be changed), which is the main purpose of this site. However, this license is really not useful for publishing the examples, since the main purpose for publishing those is to allow people to create derivatives, isn't it?

That (and the fact that all P4 Studio SDE users do have access to those examples) resulted in our decision to remove them from this repository.
