### ISSUE TITLE
How can I shift data in register?

### ISSUE THREAD

**Issue by KatherineJXY** [barefootnetworks/Open-Tofino#25]
I have trouble when compiling my p4 program in tna. I want to left-shift data and write the result into the register. But I got the error information: "expression too complex for register action: reg_data = reg_data << LEFT_SHIFT;"

**Comment by vgurevich** [comment]
@KatherineJXY -- this repository exists so that we can publish our specifications and interfaces. 

Any specific questions about Tofino hardware features, or features of its SDE or P4Studio, are best directed to Intel-specific forums created for this purpose. Please, use the following:

* [Intel Premier Support](https://premiersupport.intel.com/) if you are a commercial customer
* [ICRP Forum](https://community.intel.com/t5/Intel-Connectivity-Research/bd-p/connectivity-research-programforum-board) if you are an academic customer
